apiVersion: apps/v1
kind: Deployment
metadata:
  name: praise-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: favorites
    component: praise-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: favorites
      component: web-praise
  template:
    metadata:
      labels:
        app: favorites
        component: web-praise
    spec:
      containers:
      - name: praise
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: praise-conf
          mountPath: /config/
        ports:
        - containerPort: 8095
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
    {{- end }}
      affinity:
        podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 10
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - favorites
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: praise-conf
        configMap:
          name: praise-conf
          items:
            - key: application.yml
              path: application.yml

