apiVersion: v1
kind: Service
metadata:
  name: praise-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8095
    name: praise
  selector:
    app: {{ .Release.Name }}
    component: web-praise

