apiVersion: v1
kind: Service
metadata:
  name: praise-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8095
    name: praise
  selector:
    app: favorites
    component: web-praise

