apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-praise-conf"
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |-
    server:
      application:
        name: praise-service
      port: 8095

    spring:
      datasource:
        url: "jdbc:mysql://{{ .Values.global.mysql.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.global.mysql.servicePort }}/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
      data:
        rest:
          basePath: /api

      logging:
        level:
          io.favorites: info

