apiVersion: v1
kind: Service
metadata:
  name: look-record-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8094
    name: look-record
  selector:
    app: favorites
    component: web-look-record

