apiVersion: v1
kind: Service
metadata:
  name: folder-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8090
    name: folder
  selector:
    release: {{ .Release.Name }}
    app: web-folder

