apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8096
    name: comment
  selector:
    app: favorites
    component: web-comment

