apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8092
    name: user
  selector:
    release: {{ .Release.Name }}
    app: web-user

