server:
  port: 8094

spring:
  datasource:
    url: jdbc:mysql://10.80.17.195/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: look-record-service

logging:
  level:
    io.favorites: info

favorites:
  base:
    path: http://localhost:{server.port}/
