server:
  port: 8094

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: look-record-service

  logging:
    level:
      io.favorites: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

favorites:
  base:
    path: http://localhost:{server.port}/
