apiVersion: v1
kind: Service
metadata:
  name: notice-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8093
    name: notice
  selector:
    app: favorites
    component: web-notice

