apiVersion: v1
kind: ConfigMap
metadata: 
  name: "{{ .Release.Name }}-web-conf"
  namespace: {{ .Release.Namespace }}
data: 
  application.yml: |-
    spring:
      application:
        name: "{{ .Release.Name }}-web-main"
    server:
      port: 8080
    eureka:
      client:
        serviceUrl:
          defaultZone: http://10.80.17.195:8761/eureka
    favorites:
      services:
        folder:
          address: "{{ .Values.services.folder.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.folder.servicePort }}"
        bookmarks:
          address: "{{ .Values.services.bookmarks.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.bookmarks.servicePort }}"
        user:
          address: "{{ .Values.services.user.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.user.servicePort }}"
        notice:
          address: "{{ .Values.services.notice.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.notice.servicePort }}"
        lookrecord:
          address: "{{ .Values.services.lookrecord.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.lookrecord.servicePort }}"
        praise:
          address: "{{ .Values.services.praise.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.praise.servicePort }}"
        follow:
          address: "{{ .Values.services.follow.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.follow.servicePort }}"
        comment:
          address: "{{ .Values.services.comment.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.services.comment.servicePort }}"
  application.properties: |-
    ######  data config start ###### 
    spring.jpa.properties.hibernate.hbm2ddl.auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
    spring.jpa.show-sql= true
    spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
    ######   data config end ###### 
    static.url = /usr/local/static
    file.profilepictures.url = file/profilepictures/
    file.backgroundpictures.url = file/backgroundpictures/
    spring.profiles.active=dev
  application-docker.properties: |-
    ######  db config start ###### 
    spring.datasource.url=jdbc:mysql://mysql:3306/favorites?useUnicode=true&characterEncoding=utf-8
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
    spring.datasource.max-active=20 
    spring.datasource.max-idle=30 
    spring.datasource.min-idle=6 
    spring.datasource.initial-size=10
    ######  db config end ######

    ######   logging config start ######
    logging.file=/usr/local/logs/favorites-web.log
    logging.level.com.favorites=INFO
    logging.level.org.springframework.web=INFO
    logging.level.org.hibernate=in
    ######   logging config end ######

    favorites.base.path=http://192.168.18.132/

    ######   file path  begin ######
    static.url=/usr/share/nginx/html/
    file.profilepictures.url=profilepictures/
    file.backgroundpictures.url=backgroundpictures/
    ######   file path end ######

    #####   mail setting begin #####
    spring.mail.host=smtp.126.com
    spring.mail.username=cloudfavorites@126.com
    spring.mail.password=
    spring.mail.port=465
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
    spring.mail.properties.mail.smtp.socketFactory.port=465
    spring.mail.self.username=\u4E91\u6536\u85CF

    mail.subject.forgotpassword=\u5BC6\u7801\u91CD\u7F6E\u90AE\u4EF6
    mail.content.forgotpassword=\u8BF7\u70B9\u51FB\u4EE5\u4E0B\u5730\u5740:<br /><a href='{0}'>\u91CD\u7F6E\u5BC6\u7801</a>
    #####   mail setting end #####

    spring.thymeleaf.cache=true
  application-dev.properties: |-
    ######  db config start ######
    #spring.datasource.url=jdbc:mysql://mysql-service.favorites2.svc.cluster.local/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    spring.datasource.url=jdbc:mysql://{{ .Values.global.mysql.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.global.mysql.servicePort }}/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    ######  db config end ######

    ######   session config start ######
    server.session-timeout=2592000
    ######   session config end ######

    ######   logging config start ###### 
    logging.file=/usr/local/zx-runtime/logs/tomcat-bussiness/favorites-web.log
    logging.level.com.favorites=INFO
    logging.level.org.springframework.web=INFO
    logging.level.org.hibernate=INFO
    ######   logging config end ###### 

    favorites.base.path=http://192.168.18.132:30088/
    forgotpassword.url=http://192.168.18.132:30088/newPassword

    ######   file path  begin ######
    static.url=E:\\temp\\
    file.profilepictures.url=profilepictures/
    file.backgroundpictures.url=backgroundpictures/
    ######   file path end ######


    #####   mail setting begin #####
    spring.mail.host=smtp.126.com
    spring.mail.username=cloudfavorites@126.com
    spring.mail.password=ritesxxx123
    spring.mail.port=465
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
    spring.mail.properties.mail.smtp.socketFactory.port=465
    spring.mail.self.username=\u4E91\u6536\u85CF
    mail.subject.forgotpassword=\u5BC6\u7801\u91CD\u7F6E\u90AE\u4EF6
    mail.content.forgotpassword=\u8BF7\u70B9\u51FB\u4EE5\u4E0B\u5730\u5740:<br /><a href='{0}'>\u91CD\u7F6E\u5BC6\u7801</a>
    #####   mail setting end #####

    spring.thymeleaf.cache=false
  

