spring:
  application:
    name: favorites-web-main
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka