apiVersion: v1
kind: Service
metadata:
  name: follow-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8097
    name: follow
  selector:
    release: {{ .Release.Name }}
    app: web-follow

