apiVersion: v1
kind: Service
metadata:
  name: favorites-web-service
  namespace: {{ .Release.Namespace }}
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    name: favorites-web-service
  selector:
    release: {{ .Release.Name }}
    app: "web-{{ .Release.Name }}"

