apiVersion: v1
kind: Service
metadata:
  name: folder-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8090
    name: folder
  selector:
    app: favorites
    component: web-folder

