apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: look-record-service
  namespace: {{ .Release.Namespace }}
spec:
  host: look-record-service
  subsets:
  - name: product
    labels:
      canary: "false"
  - name: canary
    labels:
      canary: "true"
