apiVersion: v1
kind: Service
metadata:
  name: look-record-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8094
    name: look-record
  selector:
    release: {{ .Release.Name }}
    app: web-look-record

