server:
  application:
    name: user-service
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      basePath: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  logging:
    level:
      io.favorites: info

