server:
  port: 8092

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://10.80.17.195:3306/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka: #eureka
  client:
    serviceUrl:
      defaultZone: http://10.80.17.195:8761/eureka

management: #actuator
  server:
    port: 9001
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

endpoints:
  enabled: true
  info:
    sensitive: false
  health:
    sensitive: false

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

logging:
  level:
    io.favorites: info

