replicaCount: 1

global:
  namespace: favorites2
  mysql:
    serviceName: mysql-service
    servicePort: 3306
  postfixServiceName: svc.cluster.local

image:
  repository: 10.80.17.195/favorites/favorites-web
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

imagePullSecrets: 
  - favorites-docker-registry

services: 
  folder: 
    serviceName: folder-service
    servicePort: 8090
  bookmarks: 
    serviceName: bookmark-service
    servicePort: 8091
  user: 
    serviceName: user-service
    servicePort: 8092
  notice: 
    serviceName: notice-service
    servicePort: 8093
  lookrecord:
    serviceName: look-record-service
    servicePort: 8094
  praise: 
    serviceName: praise-service
    servicePort: 8095
  follow: 
    serviceName: follow-service
    servicePort: 8097
  comment:
    serviceName: comment-service
    servicePort: 8096

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
