apiVersion: v1
kind: Service
metadata:
  name: follow-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8097
    name: follow
  selector:
    app: favorites
    component: web-follow

