spring:
  application:
    name: favorites-web-main
  redis:
    host: localhost
    port: 6379
    password: 
  session:
    store-type: none
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8080

favorites:
  services:
    folder:
      address: localhost:8090
    bookmarks:
      address: localhost:8091
    user:
      address: localhost:8092
    notice:
      address: localhost:8093
    lookrecord:
      address: localhost:8094
    praise:
      address: localhost:8095
    comment:
      address: localhost:8096
    follow:
      address: localhost:8097
