spring:
  application:
    name: favorites-web-main
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8080

favorites:
  services:
    folder:
      address: localhost:8090
    bookmarks:
      address: localhost:8091
    user:
      address: localhost:8092
    notice:
      address: localhost:8093
    lookrecord:
      address: localhost:8094
    praise:
      address: localhost:8095
    follow:
      address: localhost:8097
