replicaCount: 1

image:
  repository: 10.80.17.195/favorites/user-service
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

imagePullSecrets:
  - favorites-docker-registry

applicationYml:
  server: 
    port: 8092
  spring: 
    application: 
      name: user-service
    datasource: 
      url: jdbc:mysql://mysql-service.favorites.svc.cluster.local:3306/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    jpa: 
      hibernate: 
        ddl-auto: update
      show-sql: true
  logging: 
    level: 
      io.favorites: debug
