server: 
  application: 
    name: praise-service
  port: 8095

spring: 
  datasource: 
#    url: jdbc:mysql://10.244.2.61:3306/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    url: jdbc:mysql://mysql-service.favorites.svc.cluster.local:3306/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
  data: 
    rest: 
      basePath: /api

  logging: 
    level: 
      io.favorites: info
