apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookmark-service
  namespace: {{ .Release.Namespace }}
spec:
  host: bookmark-service
  subsets:
  - name: product
    labels:
      canary: "false"
      version: {{ if .Values.global.product.version }} {{ .Values.global.product.version }} {{ else }} {{ .Values.product.version }} {{ end }}
  - name: canary
    labels:
      canary: "true"
      version: {{ if .Values.global.canary.version }} {{ .Values.global.canary.version }} {{ else }} {{ .Values.canary.version }} {{ end }}
