apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-mysql-conf"
  namespace: {{ .Release.Namespace }}
data:
  my.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    symbolic-links=0
    pid-file=/var/run/mysqld/mysqld.pid
    character_set_server=utf8
    character_set_filesystem=utf8
    collation-server=utf8_general_ci
    init-connect='SET NAMES utf8'
    init_connect='SET collation_connection = utf8_general_ci'
    skip-character-set-client-handshake
    max_connections=1000
