apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-favorites
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mysql-favorites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod-favorites
  template:
    metadata:
      labels:
        app: mysql-pod-favorites
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3306
          hostPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "favorites"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
        - mountPath: /etc/mysql/
          name: mysql-conf
      volumes:
      - name: mysql-volume
        hostPath:
          path: /mysql_volume
      - name: mysql-conf
        configMap:
          name: mysql-conf
      nodeSelector:
        app: db
