apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-comment-deploy"
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: "{{ .Release.Name }}-comment-deploy"
    version: product
spec:
  replicas: {{ .Values.global.replicaCount.comment.product }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: web-comment
      canary: "false"
      version: product
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: web-comment
        canary: "false"
        version: product
    spec:
      containers:
      - name: comment
        image: "{{ .Values.global.image.comment.repository.product }}:{{ .Values.global.image.comment.tag.product }}"
        imagePullPolicy: {{ .Values.global.image.comment.pullPolicy }}
        volumeMounts:
        - name: "{{ .Release.Name }}-comment-conf"
          mountPath: /config/
        ports:
        - containerPort: 8096
    {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
    {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: DoesNotExist
                values: []
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: "{{ .Release.Name }}-comment-conf"
        configMap:
          name: "{{ .Release.Name }}-comment-conf"
          items:
            - key: application.yml
              path: application.yml

