apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8096
    name: comment
  selector:
    release: {{ .Release.Name }}
    app: web-comment

