apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-notice-conf"
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |-
    server.application.name=notice-service
    server.port=8093
    spring.jpa.properties.hibernate.hbm2ddl.auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
    spring.jpa.show-sql= true
    spring.datasource.hikari.connectionInitSql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
    ######   data config end ######

    spring.profiles.active=dev
  application-dev.properties: |-
    ######  db config start ######
    spring.datasource.url=jdbc:mysql://{{ .Values.global.mysql.serviceName }}.{{ .Release.Namespace }}.{{ .Values.global.postfixServiceName }}:{{ .Values.global.mysql.servicePort }}/favorites?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    ######  db config end ######

    ######   session config start ######
    server.session-timeout=2592000
    ######   session config end ######

    #####   mail setting begin #####
    spring.mail.host=smtp.126.com
    spring.mail.username=cloudfavorites@126.com
    spring.mail.password=ritesxxx123
    spring.mail.port=465
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
    spring.mail.properties.mail.smtp.socketFactory.port=465
    spring.mail.self.username=\u4E91\u6536\u85CF
    mail.subject.forgotpassword=\u5BC6\u7801\u91CD\u7F6E\u90AE\u4EF6
    mail.content.forgotpassword=\u8BF7\u70B9\u51FB\u4EE5\u4E0B\u5730\u5740:<br /><a href='{0}'>\u91CD\u7F6E\u5BC6\u7801</a>
    #####   mail setting end #####

    spring.thymeleaf.cache=false

