apiVersion: v1
kind: Service
metadata:
  name: notice-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8093
    name: notice
  selector:
    release: {{ .Release.Name }}
    app: web-notice

