apiVersion: apps/v1
kind: Deployment
metadata:
  name: look-record-deploy
  namespace: favorites
  labels:
    app: look-record-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-look-record
  template:
    metadata:
      labels:
        app: web-look-record
    spec:
      containers:
      - name: look-record
        image: favorites/look-record-service:0.0.1-SNAPSHOT
#        volumeMounts:
#        - name: look-record-conf
#          mountPath: /config/
        imagePullPolicy: Never
        ports:
        - containerPort: 8094
 #     volumes:
 #     - name: look-record-conf
 #       configMap:
 #         name: look-record-conf
 #         items:
 #           - key: application.yml
 #             path: application.yml
#            - key: application.properties
#              path: application.properties
