apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8091
    name: bookmark
  selector:
    app: {{ .Release.Name }}
    component: web-bookmark

