apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8091
    name: bookmark
  selector:
    app: favorites
    component: web-bookmark

