apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: favorites
    component: user-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: favorites
      component: web-user
  template:
    metadata:
      labels:
        app: favorites
        component: web-user
    spec:
      containers:
      - name: user
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: user-conf
          mountPath: /config/
        ports:
        - containerPort: 8092
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - favorites
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: user-conf
        configMap:
          name: user-conf
          items:
            - key: application.yml
              path: application.yml

