apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-user-deploy"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: "{{ .Release.Name }}-user-deploy"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: web-user
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: web-user
    spec:
      containers:
      - name: user
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: "{{ .Release.Name }}-user-conf"
          mountPath: /config/
        ports:
        - containerPort: 8092
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
    {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: DoesNotExist
                values: []
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: "{{ .Release.Name }}-user-conf"
        configMap:
          name: "{{ .Release.Name }}-user-conf"
          items:
            - key: application.yml
              path: application.yml

