apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8092
    name: user
  selector:
    app: favorites
    component: web-user

